service: excalibur

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 29 # limited by api gateway, hard limit is 29s
  region: ap-northeast-1

plugins:
- serverless-webpack

custom:
  webpack:
    includeModules: true

functions:
  excalibur:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
