service: excalibur

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1

package:
  exclude:
    - ./**
  include:
    - node_modules/**
    - dist/**

functions:
  excalibur:
    handler: dist/bundle.handler
    events:
      - http: ANY /
